### ISSUE TITLE
Proposed changes to the API

### ISSUE THREAD

**Issue by jonyt** [aws/aws-iot-device-sdk-java-v2#117]
I've been working with the SDK for a few months now. Here are a couple of problems with the API I think should be fixed:

1. It's possible to pass in a proxy to `AwsIotMqttConnectionBuilder `and then not pass it to `X509CredentialsProvider.X509CredentialsProviderBuilder`. I can't think of a use case where I'd want the actual connection to go via proxy but not the authorization but even if there is it's probably the less common use case. It would be better to have a default where if a proxy is used it's used for everything. Otherwise you're providing the user with a footgun (which I used of course).
1. It's possible to pass in a certificate to the `AwsIotMqttConnectionBuilder` as well as `X509CredentialsProvider.X509CredentialsProviderBuilder` in which case the connection will [*sometimes* fail on TLS negotiation](https://github.com/aws/aws-iot-device-sdk-java-v2/issues/116). The sensible default would've been allowing the user to pass the certificate to one builder, but not both.

**Comment by bretambrose** [comment]
I agree we need more safety in validation/verification of configuration.  These are both a bit problematic though because the builder has no notion of what kind of credentials provider it's been given.  Checking types and dynamic casting feels a bit clumsy, and any kind of coupling between aws iot mqtt connections and the credentials providers (which have a broader intended audience) is also undesirable.
