### ISSUE TITLE
Memory leak 

### ISSUE THREAD

**Issue by Gattsus** [aws/aws-iot-device-sdk-java-v2#339]
### Describe the bug

We found a memory leak, when use mqtt connection , so we think the problem is inside something in C code.

### Expected Behavior

Memory RAM release

### Current Behavior

This connection doesn´t close, and the memory in JJVM cannot release

### Reproduction Steps

``` java
import org.slf4j.LoggerFactory
import org.springframework.beans.factory.annotation.Value
import org.springframework.stereotype.Service
import software.amazon.awssdk.crt.mqtt.MqttClientConnection
import software.amazon.awssdk.iot.AwsIotMqttConnectionBuilder
import java.time.Duration
import java.util.*
import java.util.concurrent.Semaphore
import java.util.concurrent.TimeUnit

@Service
class AwsIoTConnectionFactory(

    @Value("\${cloud.aws.region.static}")
    private val region: String = "us-east-1",

    @Value("\${cloud.aws.iot.client-id-prefix}")
    private val clientIdPrefix: String = "",

    @Value("\${cloud.aws.iot.endpoint}")
    private val iotEndpoint: String = "",

    @Value("\${cloud.aws.iot.protocol.operation-timeout-ms}")
    private val protocolOperationTimeoutMs: Int = 60000,

    @Value("\${cloud.aws.iot.connection.concurrency}")
    private val concurrentConnections: Int = 500,

    @Value("\${cloud.aws.iot.connection.acquire-timeout-ms}")
    private val acquireTimeoutMs: Long = 5000,

    @Value("\${cloud.aws.iot.session.timeout-seconds}")
    val iotSessionTimeoutSeconds: Long = Duration.ofHours(1).seconds

) {

    private val semaphore = Semaphore(concurrentConnections)

    private fun newConnection() = AwsIotMqttConnectionBuilder
        .newDefaultBuilder()
        .withClientId(clientIdPrefix + UUID.randomUUID())
        .withEndpoint(iotEndpoint)
        .withProtocolOperationTimeoutMs(protocolOperationTimeoutMs)
        .withWebsockets(true)
        .withWebsocketSigningRegion(region)
        .build()

    fun <T> getConnectionAndUse(scope: (MqttClientConnection) -> T): T {
        if (semaphore.tryAcquire(acquireTimeoutMs, TimeUnit.MILLISECONDS)) {
            newConnection().use { conn ->
                try {
                    conn.connect().get()
                    return scope(conn)
                } finally {
                    semaphore.release()
                    conn.disconnect().get()
                }
            }
        } else {
            throw HalException(HalErrorType.MAX_IOT_CONNECTIONS_IN_USE)
        }
    }

    companion object {
        val log = LoggerFactory.getLogger(AwsIoTConnectionFactory::class.java)!!
    }
}
```

### Additional Information/Context

```java
buildscript {
    ext {
        kotlin_version = "1.4.31"
        spring_boot_version = "2.2.6.RELEASE" 
        test_containers_version = "1.15.2"
        ext['log4j2.version'] = '2.15.0'
        apollo_version = "2.5.11"
        shedlock_version = "4.34.0"
    }

    dependencies {
        classpath "com.amazonaws:aws-java-sdk-core:1.11.5"
        classpath "org.jetbrains.kotlin:kotlin-noarg:$kotlin_version"
    }
}
```

### SDK version used

 implementation "software.amazon.awssdk.iotdevicesdk:aws-iot-device-sdk:1.10.5"

### Environment details (OS name and version, etc.)

linux ubuntu 20 lts

**Comment by jmklix** [comment]
Can you make sure to close the connection before stopping the program as shown in the [PubSub sample](https://github.com/aws/aws-iot-device-sdk-java-v2/blob/46fa2efb4c06adfbe82d07ff357946ae5c855e0b/samples/BasicPubSub/src/main/java/pubsub/PubSub.java#L131-L132):

```java
            // Close the connection now that we are completely done with it.
            connection.close();
```

**Comment by Gattsus** [comment]
// Close the connection now that we are completely done with it.
            connection.close();

We already tried to close the connection and that didn't work either

**Comment by Gattsus** [comment]
We used the method

newConnection().use()

From kotlin, which executes the lambda passed from argument and then calls .close() on the object

**Comment by TwistedTwigleg** [comment]
Can you share the code where `close()` is being called? Based on the code shared so far, I think you need the `getConnectionAndUse` function to look something like this:

~~~ java
fun <T> getConnectionAndUse(scope: (MqttClientConnection) -> T): T {
        if (semaphore.tryAcquire(acquireTimeoutMs, TimeUnit.MILLISECONDS)) {
            newConnection().use { conn ->
                try {
                    conn.connect().get()
                    return scope(conn)
                } finally {
                    semaphore.release()
                    conn.disconnect().get()
                    // NEW: Close the connection fully to free resources
                    conn.close()
                }
            }
        } else {
            throw HalException(HalErrorType.MAX_IOT_CONNECTIONS_IN_USE)
        }
    }
~~~

So that way, the connection is for sure closed after being disconnected and no longer needed.

Thinking about it, another possibility: The `AwsIotMqttConnectionBuilder` is **also** a CRT Resource that needs to have `close()` called on it when you are done using it, otherwise it will stick around. That might be what is causing the issue in this case. On a whole, anything that extends `CrtResource` needs to have `close()` called on it when you are no longer using it.

_______

A way you can check to see if you have `CrtResource` (like the MQTT connection) objects hanging around and not being properly freed is to add the following code at the end of your application run ([example](https://github.com/aws/aws-iot-device-sdk-java-v2/blob/main/samples/BasicPubSub/src/main/java/pubsub/PubSub.java#L138)), after all the code has executed:

~~~
CrtResource.waitForNoResources();
~~~

And then run your code with: `-Daws.crt.debugnative=true -Daws.crt.log.destination=Stdout -Daws.crt.log.level=Error`. This will help indicate if there are CRT resources hanging around that need to have `close()` called on them or not.
