### ISSUE TITLE
Custom headers support for AWS iot custom authentication

### ISSUE THREAD

**Issue by aloysiustany** [aws/aws-iot-device-sdk-java-v2#43]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-java-v2/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
MacOS Catalina

**Describe the question**
I am trying to use the custom authentication (https://docs.aws.amazon.com/iot/latest/developerguide/custom-auth.html) to authenticate my devices. 
As per the instructions, we need to set few headers such as 
- x-amz-customauthorizer-name: \<authorizer-name>
- x-amz-customauthorizer-signature: \<token-signature>
- \<token-key-name>: \<some-token>

I am trying to figure out how to set these headers in the SDK.
As per RawPubSub sample, setting --auth_params should set as headers but when I looked at the sample code, it does not use this argument when there is no username set.

Any guidance or sample would be of much help.

**Comment by bretambrose** [comment]
It looks like we forgot to add a transform configuration element to the mqtt client builder.  Assuming that existed, you'd supply your own function there that added the appropriate header elements to the handshake request.

**Comment by aloysiustany** [comment]
Thanks @bretambrose for the response. This means I have to wait for the (next ?) sdk update to hook up a transform function.

**Comment by bretambrose** [comment]
Until that's implemented, as a workaround, you can skip using the builder and create the mqtt client by hand.  Take a look at https://github.com/aws/aws-iot-device-sdk-java-v2/blob/master/sdk/src/main/java/software/amazon/awssdk/iot/AwsIotMqttConnectionBuilder.java#L400 to see how the manual process works.  If you subclass the transformer (used at https://github.com/aws/aws-iot-device-sdk-java-v2/blob/master/sdk/src/main/java/software/amazon/awssdk/iot/AwsIotMqttConnectionBuilder.java#L458) to add the parameters you need to the request before letting the base class do the signing, you should be able to make progress.

**Comment by bretambrose** [comment]
Revisiting this issue, I apologize I think I gave you bad advice.  It turns out that the transform was settable on the connection builder all along:

https://github.com/aws/aws-iot-device-sdk-java-v2/blob/master/sdk/src/main/java/software/amazon/awssdk/iot/AwsIotMqttConnectionBuilder.java#L342

In particular, you can set that to a function that can arbitrarily mutate the handshake request (add your headers) and when you're done, call complete() on the contained future and the handshake will be sent.

As an example of an existing transform, you can look at the sigv4 signing transform (which you don't need since you're doing custom auth): https://github.com/aws/aws-iot-device-sdk-java-v2/blob/master/sdk/src/main/java/software/amazon/awssdk/iot/AwsSigv4HandshakeTransformer.java#L41
