### ISSUE TITLE
IoT doesn't like newline character in device cert

### ISSUE THREAD

**Issue by xinguaws** [aws/aws-iot-device-sdk-java-v2#70]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-java-v2/issues) and didn't find any solution

**Describe the bug**
**To Reproduce (observed behavior)**
step 1: 
openssl genrsa -out ./private.key 2048
openssl req -new -key private.key -out ./sample.csr
aws iot create-certificate-from-csr --certificate-signing-request=file://sample.csr, in the response I will receive the certificatePem and I saved it to a file "cert.pem":
"certificatePem": "-----BEGIN CERTIFICATE-----\nblablablablablabla=\n-----END CERTIFICATE-----\n"
step 2: activate my device cert and attach IoT policy so I can test
step 3: mvn exec:java -pl samples/BasicPubSub -Dexec.mainClass=pubsub.PubSub -Dexec.args="--endpoint xxxxx-ats.iot.us-east-1.amazonaws.com --clientId clientID --cert cert.pem --key private.key"

Here is the error I got:
Exception encountered: software.amazon.awssdk.crt.CrtRuntimeException: TlsContext.tls_ctx_new: Failed to create new aws_tls_ctx (aws_last_error: AWS_IO_TLS_CTX_ERROR(1033), Failed to create tls context)

**Workaround**
If I log into IoT console and download the cert.pem there, it works fine. I was able to connect/pub/sub. The cert.pem which has issues contains literal newline character \n, the one downloaded have actually multiple lines. I am not sure if this is indeed an issue? Does the device certificate pem file has to follow:
-----BEGIN CERTIFICATE-----
blablablablablabla
-----END CERTIFICATE-----
NOT:
-----BEGIN CERTIFICATE-----\nblablablablablabla=\n-----END CERTIFICATE-----\n
?

**SDK version number**
1.2.0

**Platform/OS/Hardware/Device**
Linux+Windows

**Comment by bretambrose** [comment]
I just ran into the same issue when calling CreateProvisioningClaim.

If I understand this properly, what you see in the output from the cli has been escaped, in particular the newlines.  Our pem parser is not going to treat the escaped newlines like actual newlines and that is likely what the problem is.  In an ideal situation, there would be an easy way to unescape and extract all of the components into a set of files.  

I don't know what the best answer is at the moment, but I'll bring it up to the team.  The first possibility that comes to mind is a simple script that you could pipe cli output into and get the triplet of cert/pubkey/privatekey files properly formatted.  But maybe there's something better we could do to support this.

**Comment by bretambrose** [comment]
I whipped up a quick script to get around having to manually edit the returned pem values: https://github.com/aws/aws-iot-device-sdk-python-v2/pull/81/files#diff-95c2ff54d480190c6d4b1816bf2fffe3

Depending on the team's reaction, we may add this as a utility to all the sdks or it may get banished somewhere.  But for now, feel free to use it.
