### ISSUE TITLE
Can we run Java-v2 SDK for Android App?

### ISSUE THREAD

**Issue by AagamMehta** [aws/aws-iot-device-sdk-java-v2#85]
Hello,
    I am an embedded developer. I have designed an IoT system with few micro-controllers (as IoT Device) and Raspberry Pi (as GreenGrassCore). I can successfully communicate between devices (via core) through MQTT pub-sub _(Note - Since all these devices are connected on the same network the communication works irrespective of the availability of internet)_. Now, to move a step ahead I am learning Android and communicate messages from/to Android App to IoT Devices (via GreenGrassCore). To test the feasibility I used the [Python SDK for GreenGrass](https://github.com/aws/aws-greengrass-core-sdk-python) and ran the sample code on Laptop and it executed successfully as expected. The communication worked with or without the availability of the Internet. Now I want the same thing to be coded for Android. Is the Java-V2 SDK the correct thing to start from? If yes, can you specify some examples and developer guide for GreenGrassCommunication? If no, can you please help with an alternate way around to make it work?

Thanking you in advance.

**Comment by rajkumu12** [comment]
I have imported android project into my android studio synced it is giving following issue what should i do

Failed to resolve: software.amazon.awssdk.crt:android:0.6.2
Show in Project Structure dialog
Affected Modules: app

i tried every possible thing it didn't work

**Comment by bretambrose** [comment]
The V2 Java SDK is the next iteration of https://github.com/aws/aws-iot-device-sdk-java and is not a replacement for https://github.com/aws/aws-greengrass-core-sdk-python

If you're looking for something similar for Java, I would check out https://github.com/aws/aws-greengrass-core-sdk-java

**Comment by AagamMehta** [comment]
Okay, @bretambrose, understood that point but I wanted some guidance on if I will be able to run the aws-greengrass-core-sdk-java on the android app? If not then what is the way to run GreenGrassCore communication (offline) with an Android App?

Really hoping for some guidance in this matter. Thanks in advance.

**Comment by bretambrose** [comment]
I would ask on that repository; it's built/supported by a different team.

**Comment by AagamMehta** [comment]
Okay, I am asking on the AWS GreenGrassCore SDK for Java repository. So, as for final confirmation, This repo isn't meant for Android - GreenGrassCore communication? Since in the repo there are Android folder and also GreenGrassCore sample too... Can you please clarify that?

Thanks for the cooperation so far.

**Comment by bretambrose** [comment]
I believe the v2 SDK can use the gg core as a mqtt broker through the use of the discovery client, but the v2 sdk has no support for lambda-related functionality.

**Comment by AagamMehta** [comment]
Lemme specify the complete setup that we have tested and thereby explain the requirement for better clarity.

For testing the Offline Communication between IoT devices in the same network using Greengrass Core as an Offline Broker, we followed [Module 5 : Interacting with device shadows](https://docs.aws.amazon.com/greengrass/latest/developerguide/module5.html) of AWS IoT Greengrass.

![bd-ggc](https://user-images.githubusercontent.com/43824188/88776048-1925bf00-d1a3-11ea-8de1-d869cef50460.png)

As shown in the above diagram, Light switch device and Traffic light device communicate with each other even when there is no Internet connectivity. To suit our application, we modified the code (attached in the zipped folder below) of Light switch device (Original Code - [lightController.py](https://github.com/aws/aws-greengrass-core-sdk-python/blob/master/examples/TrafficLight/lightController.py) ; Modified Code - [lightController.zip](https://github.com/aws/aws-iot-device-sdk-java-v2/files/4993640/lightController.zip)) and instead of having another Laptop as an IoT Device for Traffic light device, we used ESP32 micro-controller running custom Amazon FreeRTOS code (which subscribes to a predefined topic and prints the received messages).


![LSU](https://user-images.githubusercontent.com/43824188/88776987-58a0db00-d1a4-11ea-9832-910b5d4b3e40.png)

In the above picture, the left console prints the logs of the lightController.py file (modified to publish a value variable to predefined topic) is running on Laptop and the right console is the Serial Monitor of the IoT Device (ESP32) running Amazon FreeRTOS. There is a Raspberry Pi 3B+ which is running Greengrass Core Software. These 3 devices are on the same WiFi network. Here, Laptop is the publisher which publishes MQTT messages every 20 seconds to a pre-defined topic. ESP32 is the subscriber which has subscribed to that pre-defined topic. Raspberry Pi acts as the Offline MQTT Broker when there is no internet connectivity. We tested this setup with and without Internet connectivity. When there is no internet connection the messages are still communicated from Laptop (publisher) to the IoT Device (Subscriber) via GreenGrass Core (Raspberry Pi) where Greengrass Core acts as Offline MQTT Broker to facilitate the communication.

This setup has worked seamlessly.

Now, we want to have a Mobile App (Android) as the Publisher instead of a Laptop. Laptop used [aws-iot-device-sdk-python](https://github.com/aws/aws-iot-device-sdk-python) but the same cannot be used in an Android App. Hence, we want to find a similar aws-iot-device-sdk to make it run on Android. We found that there is also aws-iot-device-sdk-java-v2 which has Greengrass Sample Code similar to AWS-IoT-Device SDK for Python.

Queries
1) Is the aws-iot-device-sdk-java-v2 the correct way ahead for an Android App?
2) If yes, then how to execute the GreenGrass Communication Sample Code in Android? A developer guide will be highly helpful for this.
3) If no, then what is the correct way ahead to develop an Android App to communicate locally with GreenGrassCore and other IoT devices?

Really hoping guidance on this since I ain't able to find suitable guide online. Thanking you in advance.

**Comment by bretambrose** [comment]
Thank you for the very detailed followup; it makes your use case much clearer.

You originally mentioned the Greengrass SDK (https://github.com/aws/aws-greengrass-core-sdk-python) but in the most recent followup you mentioned the v1 IoT SDK (https://github.com/aws/aws-iot-device-sdk-python).  Based on your detailed description, it now sounds like you used the IoT SDK, but I just wanted to verify that that's the case?

The v2 sdk can perform basic mqtt and IoT data service (shadow, jobs, identity/provisioning) operations to an arbitrary endpoint, so if a greengrass core proxies (or implements) the service, you can certainly use the v2 SDK for that.  Based on the docs, it looks like shadow is the only IoT data service incorporated into greengrass, so you should be able to use the v2 SDK.  I do not know if greengrass supports the recently-released named-shadow functionality though.

Android support is a work-in-progress.  Building for android is possible but requires a number of manual steps because we don't yet publish android-specific packages to maven (in particular, you have to build the aws crt -- https://github.com/awslabs/aws-crt-java -- which has a lot of native dependencies and requires the NDK).  There's an open issue right now that details the build steps (https://github.com/aws/aws-iot-device-sdk-java-v2/issues/87)

Beyond that, we are actively working on improving the docs and onboarding experience, and (once the publishing issue is resolved) something Android-oriented would be really useful, but I don't have any kind of ETA.  We'll do what we can to help resolve issues you encounter and welcome any feedback based on your experiences.

**Comment by rajkumu12** [comment]
Thanks for your support
I have followed all including configuring ndk but still getting issue with setup this project

Failed to resolve: software.amazon.awssdk.crt:android:0.6.5
Show in Project Structure dialog
Affected Modules: app

Overall issue is I am not able to run this project
So that i can't see any log.
